### ISSUE TITLE
It looks like bullet are not styled to the right color when setting the word 

### ISSUE THREAD

**Issue by Oleafeon** [new-data-services/statamic-bard-color-picker#2]
![image](https://user-images.githubusercontent.com/20043831/232746565-5f231d66-dee4-4d73-b46f-f72cc5b86894.png)

is there a way to get this right

**Comment by heidkaemper** [comment]
Hi Olivia. Thank's for reporting this.
I think this one could be a little tricky. Our addon probably will have to check wether the currect text selection covers all content of a surrounding li element. And than apply the color to that li element.
But we'll have a look!

**Comment by Oleafeon** [comment]
We have created a addon so that we can select the default color that is used in that bard text field this will change the bullets also we use your addon to change a couple of words or a sentence
